In [1]:
import numpy as np

# Assuming the following variables are defined:
# N: number of countries
# theta: trade elasticity
# T: technology matrix
# d: iceberg costs matrix
# L: labor endowment vector
# w_start: initial wage vector
# gamma: constant from the utility function
# bump: adjustment factor for the wage update

N = 5
theta = 0.5
T = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
d = np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
              [0.6, 0.7, 0.8, 0.9, 1.0],
              [1.1, 1.2, 1.3, 1.4, 1.5],
              [1.6, 1.7, 1.8, 1.9, 2.0],
              [2.1, 2.2, 2.3, 2.4, 2.5]])
L = np.array([1, 2, 3, 4, 5])
w_start = np.array([0.5, 0.6, 0.7, 0.8, 0.9])
gamma = 0.2
bump = 0.1


# Initialize cost to be equal to the wage
c = w_start

# Set a NxN matrix of fob ("free-on-board") prices
p = (c**(-theta) * T) @ np.ones(N)

# Construct the matrix of deliverable prices
p = d * p

# Construct the Phi term for each destination country
Phi = np.sum(p)

# Set up the matrix of expenditure shares
Phi_mtx = np.ones((N, 1)) * Phi
pi = p / Phi_mtx

# Calculate the RHS and LHS of equation (18) in EK (2002)
RHS = pi @ (w_start * L)
LHS = w_start * L

# Calculate the loss function deviation
dev = np.sum(np.abs(LHS - RHS))

# Adjust the candidate vector
w_start = w_start - bump * (LHS - RHS)

# Normalize one wage to 1
w_start = w_start / w_start[N-1]

# Calculate the nominal wage, price index, and real wage
w_n = w_start
P_n = gamma * (Phi**(-1/theta))
real_w = w_n / P_n

In [2]:
import numpy as np

# Assuming the following variables are defined:
# Ncntry: number of countries
# Ngoods: number of goods
# invNgoods: reciprocal of the number of goods
# inveta: reciprocal of eta
# eta: trade elasticity
# sum_price: sum of prices
# m: trade matrix
# rec_low_price: matrix of lowest prices

Ncntry = 4
Ngoods = 3
invNgoods = 1 / Ngoods
inveta = 1 / 0.5
eta = 0.5
sum_price = np.array([10, 20, 30, 40])
m = np.zeros((Ncntry, Ncntry))
rec_low_price = np.array([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])


# Initialize g
g = np.zeros(Ncntry)

# Loop to calculate aggregate price index and the trade shares
for im in range(Ncntry):
    g[im] = (sum_price[im] * invNgoods) ** inveta

    for ex in range(Ncntry):
        m[ex, im] = invNgoods * m[ex, im] / g[im] ** (1 - eta)

# Compute good level shares
rec_gd_share = np.zeros((Ngoods, Ncntry))

for gd in range(Ngoods):
    for im in range(Ncntry):
        rec_gd_share[gd, im] = invNgoods * rec_low_price[gd, im] ** (1 - eta) / g[im] ** (1 - eta)

# Generate a price matrix similar to that in the data
final_price = rec_low_price.T
good_shares = rec_gd_share.T

print(final_price)
print(good_shares)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[0.1        0.2236068  0.3       ]
 [0.07071068 0.12247449 0.15811388]
 [0.05773503 0.08819171 0.11055416]
 [0.05       0.07071068 0.08660254]]
